using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace K9.Generator.GitInfo;

[Generator]
public class GitInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // TODO: This could be turned into a provider, that would cash the revision and then only add when it changed.
        // Currently this runs every build
        context.RegisterPostInitializationOutput(ctx =>
        {
            // Figure out the GIT head hash
            ProcessStartInfo startInfo = new()
            {
                FileName = "git",
                Arguments = "rev-parse HEAD",
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            string gitHash = "Unknown";
            using (Process? process = Process.Start(startInfo))
            {
                if (process != null)
                {
                    gitHash = process.StandardOutput.ReadToEnd();
                    process.WaitForExit();
                }
            }

            // We need to clean up the hash
            gitHash = gitHash.Trim();

            // Build our source content
            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("static class GitInfo {");
            sb.AppendLine($"public const string Head = \"{gitHash}\";");
            sb.AppendLine("}");

            ctx.AddSource("GitInfo.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}